### ISSUE TITLE
Linux link in readme is wrong

### ISSUE THREAD

**Issue by ernierasta** [marianogappa/gomario#1]
Hi,
congrats on first go program! Good work!

Just little bug in readme, actual link is:
https://github.com/MarianoGappa/gomario/raw/master/bin/linux/gomario
So instructructions should be changed.

Have a great day!

**Comment by Rodgelius** [comment]
Hi!
Amazing game with perfect realistic textures! Good work!
I want to be the first who will know about release second part )))
Fix linux link. it's not work)

Have a nice day!)

**Comment by marianogappa** [comment]
Thanks for the issue and the PR, everyone!
